#!/bin/bash

if [ ! -d ./build/java ]; then
    mkdir -p ./build/java
fi

javac -cp :./lib/java/*:./lib/java/jgrapht-1.4.0/* -d build/java src/java/main/*.java src/java/main/testgen/*.java src/java/main/cil/*.java src/java/main/reltestidentify/*.java src/java/main/aflscriptgen/*.java
