package edu.gatech.cc.debaug;

import java.util.List;
import java.util.ArrayList;
import java.util.Set;
import java.util.HashSet;
import java.io.File;
import org.apache.commons.io.FileUtils;

public class MakeOutputCleanup
{
    public static void main(String[] args) {
	String output_fpath = args[0];

	List<String> output_flines = null;
	try { output_flines = FileUtils.readLines(new File(output_fpath)); }
        catch (Throwable t) { System.err.println(t); t.printStackTrace(); }
        if (output_flines == null) { return; }

	int size = output_flines.size();
	for (int i=0; i<size; i++) {
	    String output_fline = output_flines.get(i).trim();
	    if (output_fline.startsWith("# Make data base, printed on") ||
		output_fline.startsWith("#  Last modified ") ||
		output_fline.startsWith("# Finished Make data base on") ||

		output_fline.startsWith("Putting child") ||
		output_fline.startsWith("Live child") ||
		output_fline.startsWith("Reaping losing child") ||
		output_fline.startsWith("Removing child")) {
		
		output_flines.set(i, ""); //Emptify to leave out time info
	    }
	}

	if (size > 1) {
	    String last_fline = output_flines.get(size-1).trim();
	    if (last_fline.equals("") ||
		last_fline.startsWith("cc = write ") ||
		last_fline.startsWith("/home/qxin6") ||
		last_fline.startsWith("Makefile:") ||
		last_fline.startsWith("Report bugs to") ||
		last_fline.startsWith("gcc ") ||
		last_fline.startsWith("make-3.79:") ||
		last_fline.startsWith("mv -f ") ||
		last_fline.startsWith("rm -f ") ||
		last_fline.startsWith("touch make")) {
		//Possibilities for last lines that are valid
		//To figure this out, I checked the last lines for all outputs
	    }
	    else {
		//Remove the bad line (seemingly generated by rm-makestuff by random)
		output_flines.remove(size-1);
	    }
	}
	
	try { FileUtils.writeLines(new File(output_fpath), output_flines); }
	catch (Throwable t) { System.err.println(t); t.printStackTrace(); }
    }
}
   
